Repository jent-ly/summarizer, pull requests merged in 2019-07, with the labels that each got.

#23 update lodash.template version
  package-lock.json
  package.json
Labels: security

#27 Dev
  package-lock.json
  package.json
  public/bg/background.js
  public/icons/icon128.png
  public/icons/icon16.png
  public/icons/icon19.png
  public/icons/icon48.png
  public/icons/jent-icon.png
  public/js/contentScript.js
  public/manifest.json
  src/components/ListTab.tsx
  src/components/MainTab.tsx
  src/components/OptionsTab.tsx
  src/components/TabPanel.tsx
  src/components/Toast.tsx
  src/containers/Popup.tsx
  src/css/popup.css
  src/css/popup.scss
  src/img/v1.1-1000x192.png
  src/img/v1.1-250x48.png
  src/img/v1.1-500x96.png
  src/img/v1.1-opq-1000x192.png
  src/img/v1.1-opq-250x48.png
  src/img/v1.1-opq-500x96.png
  src/img/v1.2-1000x192.png
  src/img/v1.2-250x48.png
  src/img/v1.2-500x96.png
  src/img/v1.2-opq-1000x192.png
  src/img/v1.2-opq-250x48.png
  src/img/v1.2-opq-500x96.png
  src/img/v1.3-1000x192.png
  src/img/v1.3-250x48.png
  src/img/v1.3-500x96.png
  src/img/v1.3-opq-1000x192.png
  src/img/v1.3-opq-250x48.png
  src/img/v1.3-opq-500x96.png
  src/img/v1.4-1000x220.png
  src/img/v1.4-250x55.png
  src/img/v1.4-500x110.png
  src/img/v1.4-opq-1000x220.png
  src/img/v1.4-opq-250x55.png
  src/img/v1.4-opq-500x110.png
  src/img/v1.5-1000x220.png
  src/img/v1.5-opq-1000x220.png
  src/img/v1.6-opq-1000x220.png
  tsconfig.json
  yarn.lock
Labels: enhancement

#29 Fix update between tabs
  src/containers/Popup.tsx
Labels: bug
